//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JetBrainsRecentProjectCmdPal.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JetBrainsRecentProjectCmdPal.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to set clipboard content, another program may have control.
        /// </summary>
        internal static string clipboard_failed {
            get {
                return ResourceManager.GetString("clipboard_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy path.
        /// </summary>
        internal static string copy_path {
            get {
                return ResourceManager.GetString("copy_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path copied to clipboard..
        /// </summary>
        internal static string copy_path_ok {
            get {
                return ResourceManager.GetString("copy_path_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JetBrains Recent Projects.
        /// </summary>
        internal static string jetbrains_recent_projects_name {
            get {
                return ResourceManager.GetString("jetbrains_recent_projects_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JetBrains Recent Projects.
        /// </summary>
        internal static string jetbrains_recent_projects_title {
            get {
                return ResourceManager.GetString("jetbrains_recent_projects_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run as.
        /// </summary>
        internal static string msg_run_as {
            get {
                return ResourceManager.GetString("msg_run_as", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run as administrator.
        /// </summary>
        internal static string msg_run_as_administrator {
            get {
                return ResourceManager.GetString("msg_run_as_administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Path.
        /// </summary>
        internal static string project_path_label {
            get {
                return ResourceManager.GetString("project_path_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to execute as admin.
        /// </summary>
        internal static string run_admin_exception {
            get {
                return ResourceManager.GetString("run_admin_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to execute as user.
        /// </summary>
        internal static string run_as_exception {
            get {
                return ResourceManager.GetString("run_as_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search {0} recent projects....
        /// </summary>
        internal static string search_recent_projects_placeholder {
            get {
                return ResourceManager.GetString("search_recent_projects_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom VM Options.
        /// </summary>
        internal static string settings_custom_vmoptions {
            get {
                return ResourceManager.GetString("settings_custom_vmoptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show last opened time.
        /// </summary>
        internal static string settings_display_last_time {
            get {
                return ResourceManager.GetString("settings_display_last_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show item names.
        /// </summary>
        internal static string settings_display_project_name {
            get {
                return ResourceManager.GetString("settings_display_project_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each tool group.
        /// </summary>
        internal static string settings_jetbrains_product_archive {
            get {
                return ResourceManager.GetString("settings_jetbrains_product_archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run as administrator.
        /// </summary>
        internal static string settings_run_as_administrator {
            get {
                return ResourceManager.GetString("settings_run_as_administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shell scripts location.
        /// </summary>
        internal static string settings_shell_script_location {
            get {
                return ResourceManager.GetString("settings_shell_script_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync JetBrains Toolbox.
        /// </summary>
        internal static string settings_sync_jetbrains_toolbox {
            get {
                return ResourceManager.GetString("settings_sync_jetbrains_toolbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System config and logs directory.
        /// </summary>
        internal static string settings_systemconfiglogs_directory {
            get {
                return ResourceManager.GetString("settings_systemconfiglogs_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools installation locations.
        /// </summary>
        internal static string settings_tools_install_location {
            get {
                return ResourceManager.GetString("settings_tools_install_location", resourceCulture);
            }
        }
    }
}
