//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JetBrainsRecentProjectCmdPal.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JetBrainsRecentProjectCmdPal.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm.
        /// </summary>
        internal static string alarm_label {
            get {
                return ResourceManager.GetString("alarm_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build.
        /// </summary>
        internal static string build_label {
            get {
                return ResourceManager.GetString("build_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to set clipboard content, another program may have control.
        /// </summary>
        internal static string clipboard_failed {
            get {
                return ResourceManager.GetString("clipboard_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy path.
        /// </summary>
        internal static string copy_path {
            get {
                return ResourceManager.GetString("copy_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path copied to clipboard.
        /// </summary>
        internal static string copy_path_ok {
            get {
                return ResourceManager.GetString("copy_path_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string jetbrains_product_label {
            get {
                return ResourceManager.GetString("jetbrains_product_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JetBrains Recent Projects.
        /// </summary>
        internal static string jetbrains_recent_projects_name {
            get {
                return ResourceManager.GetString("jetbrains_recent_projects_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JetBrains Recent Projects.
        /// </summary>
        internal static string jetbrains_recent_projects_title {
            get {
                return ResourceManager.GetString("jetbrains_recent_projects_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last opened time.
        /// </summary>
        internal static string lasted_open_time_label {
            get {
                return ResourceManager.GetString("lasted_open_time_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in Explorer.
        /// </summary>
        internal static string msg_open_in_explorer {
            get {
                return ResourceManager.GetString("msg_open_in_explorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run as.
        /// </summary>
        internal static string msg_run_as {
            get {
                return ResourceManager.GetString("msg_run_as", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run as administrator.
        /// </summary>
        internal static string msg_run_as_administrator {
            get {
                return ResourceManager.GetString("msg_run_as_administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open in Explorer.
        /// </summary>
        internal static string open_explorer_exception {
            get {
                return ResourceManager.GetString("open_explorer_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open time.
        /// </summary>
        internal static string open_time_label {
            get {
                return ResourceManager.GetString("open_time_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product code.
        /// </summary>
        internal static string product_code_label {
            get {
                return ResourceManager.GetString("product_code_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project not found.
        /// </summary>
        internal static string project_not_found {
            get {
                return ResourceManager.GetString("project_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project path.
        /// </summary>
        internal static string project_path_label {
            get {
                return ResourceManager.GetString("project_path_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        internal static string project_status_closed {
            get {
                return ResourceManager.GetString("project_status_closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project status.
        /// </summary>
        internal static string project_status_label {
            get {
                return ResourceManager.GetString("project_status_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opened.
        /// </summary>
        internal static string project_status_opened {
            get {
                return ResourceManager.GetString("project_status_opened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project workspace ID.
        /// </summary>
        internal static string project_workspace_id_label {
            get {
                return ResourceManager.GetString("project_workspace_id_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to execute as administrator.
        /// </summary>
        internal static string run_admin_exception {
            get {
                return ResourceManager.GetString("run_admin_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to execute as user.
        /// </summary>
        internal static string run_as_exception {
            get {
                return ResourceManager.GetString("run_as_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search {0}.
        /// </summary>
        internal static string search_recent_projects_placeholder {
            get {
                return ResourceManager.GetString("search_recent_projects_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom options.
        /// </summary>
        internal static string settings_custom_options {
            get {
                return ResourceManager.GetString("settings_custom_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable custom configuration for tools installation location and system config logs directory.
        /// </summary>
        internal static string settings_custom_options_description {
            get {
                return ResourceManager.GetString("settings_custom_options_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group projects by product.
        /// </summary>
        internal static string settings_jetbrains_product_archive {
            get {
                return ResourceManager.GetString("settings_jetbrains_product_archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run as administrator.
        /// </summary>
        internal static string settings_run_as_administrator {
            get {
                return ResourceManager.GetString("settings_run_as_administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System config and logs directory.
        /// </summary>
        internal static string settings_systemconfiglogs_directory {
            get {
                return ResourceManager.GetString("settings_systemconfiglogs_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools installation location.
        /// </summary>
        internal static string settings_tools_install_location {
            get {
                return ResourceManager.GetString("settings_tools_install_location", resourceCulture);
            }
        }
    }
}
