//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JetBrainsRecentProjectCmdPal.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JetBrainsRecentProjectCmdPal.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Alarm 的本地化字符串。
        /// </summary>
        internal static string alarm_label {
            get {
                return ResourceManager.GetString("alarm_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Build 的本地化字符串。
        /// </summary>
        internal static string build_label {
            get {
                return ResourceManager.GetString("build_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to set clipboard content, another program may have control 的本地化字符串。
        /// </summary>
        internal static string clipboard_failed {
            get {
                return ResourceManager.GetString("clipboard_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy path 的本地化字符串。
        /// </summary>
        internal static string copy_path {
            get {
                return ResourceManager.GetString("copy_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Path copied to clipboard 的本地化字符串。
        /// </summary>
        internal static string copy_path_ok {
            get {
                return ResourceManager.GetString("copy_path_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 JetBrains Recent Projects 的本地化字符串。
        /// </summary>
        internal static string jetbrains_recent_projects_name {
            get {
                return ResourceManager.GetString("jetbrains_recent_projects_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 JetBrains Recent Projects 的本地化字符串。
        /// </summary>
        internal static string jetbrains_recent_projects_title {
            get {
                return ResourceManager.GetString("jetbrains_recent_projects_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last opened time 的本地化字符串。
        /// </summary>
        internal static string lasted_open_time_label {
            get {
                return ResourceManager.GetString("lasted_open_time_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open in Explorer 的本地化字符串。
        /// </summary>
        internal static string msg_open_in_explorer {
            get {
                return ResourceManager.GetString("msg_open_in_explorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run as 的本地化字符串。
        /// </summary>
        internal static string msg_run_as {
            get {
                return ResourceManager.GetString("msg_run_as", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run as administrator 的本地化字符串。
        /// </summary>
        internal static string msg_run_as_administrator {
            get {
                return ResourceManager.GetString("msg_run_as_administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to open in Explorer 的本地化字符串。
        /// </summary>
        internal static string open_explorer_exception {
            get {
                return ResourceManager.GetString("open_explorer_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open time 的本地化字符串。
        /// </summary>
        internal static string open_time_label {
            get {
                return ResourceManager.GetString("open_time_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Product code 的本地化字符串。
        /// </summary>
        internal static string product_code_label {
            get {
                return ResourceManager.GetString("product_code_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Project not found 的本地化字符串。
        /// </summary>
        internal static string project_not_found {
            get {
                return ResourceManager.GetString("project_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Project path 的本地化字符串。
        /// </summary>
        internal static string project_path_label {
            get {
                return ResourceManager.GetString("project_path_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Closed 的本地化字符串。
        /// </summary>
        internal static string project_status_closed {
            get {
                return ResourceManager.GetString("project_status_closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Project status 的本地化字符串。
        /// </summary>
        internal static string project_status_label {
            get {
                return ResourceManager.GetString("project_status_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Opened 的本地化字符串。
        /// </summary>
        internal static string project_status_opened {
            get {
                return ResourceManager.GetString("project_status_opened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Project workspace ID 的本地化字符串。
        /// </summary>
        internal static string project_workspace_id_label {
            get {
                return ResourceManager.GetString("project_workspace_id_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to execute as administrator 的本地化字符串。
        /// </summary>
        internal static string run_admin_exception {
            get {
                return ResourceManager.GetString("run_admin_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to execute as user 的本地化字符串。
        /// </summary>
        internal static string run_as_exception {
            get {
                return ResourceManager.GetString("run_as_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search {0} 的本地化字符串。
        /// </summary>
        internal static string search_recent_projects_placeholder {
            get {
                return ResourceManager.GetString("search_recent_projects_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom options 的本地化字符串。
        /// </summary>
        internal static string settings_custom_options {
            get {
                return ResourceManager.GetString("settings_custom_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable custom configuration for tools installation location and system config logs directory 的本地化字符串。
        /// </summary>
        internal static string settings_custom_options_description {
            get {
                return ResourceManager.GetString("settings_custom_options_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Group projects by product 的本地化字符串。
        /// </summary>
        internal static string settings_jetbrains_product_archive {
            get {
                return ResourceManager.GetString("settings_jetbrains_product_archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run as administrator 的本地化字符串。
        /// </summary>
        internal static string settings_run_as_administrator {
            get {
                return ResourceManager.GetString("settings_run_as_administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System config and logs directory 的本地化字符串。
        /// </summary>
        internal static string settings_systemconfiglogs_directory {
            get {
                return ResourceManager.GetString("settings_systemconfiglogs_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tools installation location 的本地化字符串。
        /// </summary>
        internal static string settings_tools_install_location {
            get {
                return ResourceManager.GetString("settings_tools_install_location", resourceCulture);
            }
        }
    }
}
